spring.application.name=user-service

# nacos
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.discovery.group=cloud-demo
spring.config.import=nacos:user-service.properties?group=cloud-demo