stages:
  - build
  - deploy

build-jar:
  stage: build
  tags:
    - aws
  script:
    - ./mvnw clean package -DskipTests

deploy:
  stage: deploy
  tags:
    - aws
  script:
    - docker compose down || true
    - docker compose build
    - docker compose up -d