stages:
  - build
  - deploy

build-jar:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  tags:
    - aws
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image: docker:latest
  tags:
    - aws
  script:
    - docker compose down || true
    - docker compose build
    - docker compose up -d