version: '3.8'
# docker compose --env-file config/.env up -d --build
services:
  # 目前機器無法承受 nacos 服務先停止
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    # 部署時變數來源是 GitLab Variables 不是 .env, 記得要設定
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=false
      - NACOS_AUTH_TOKEN=${AUTH_TOKEN}
      - NACOS_AUTH_IDENTITY_KEY=${AUTH_IDENTITY_KEY}
      - NACOS_AUTH_IDENTITY_VALUE=${AUTH_IDENTITY_VALUE}

    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"

    volumes:
      - ./nacos/data:/home/nacos/data
      - ./nacos/logs:/home/nacos/logs

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8101:8101"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      nacos:
        condition: service_healthy

  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "8102:8102"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      nacos:
        condition: service_healthy

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8100:8100"
    depends_on:
      user-service:
        condition: service_started
      order-service:
        condition: service_started

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - gateway