version: '3.8'

services:
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8101:8101"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "8102:8102"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8100:8100"
    depends_on:
      - user-service
      - order-service