spring.application.name=gateway

# nacos
spring.cloud.nacos.config.server-addr=host.docker.internal:8848
spring.cloud.nacos.discovery.server-addr=host.docker.internal:8848
spring.cloud.nacos.discovery.group=cloud-demo
spring.config.import=nacos:gateway.properties?group=cloud-demo