spring.application.name=order-service

# nacos
spring.cloud.nacos.config.server-addr=nacos:8848
spring.cloud.nacos.discovery.server-addr=nacos:8848
spring.cloud.nacos.discovery.group=cloud-demo
spring.config.import=nacos:order-service.properties?group=cloud-demo

# ????? nacos ?????
spring.cloud.nacos.discovery.fail-fast=false